config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "application_data#index"
  resources :application_data, only: [:index, :new, :create, :destroy]
  resources :application_data do
    collection do
      get "operator_info"
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <h5 class="footer-title">本サイトについて</h5>
  <div class="contact-us">
    <%= link_to "運営者情報（お問い合わせ先）", operator_info_application_data_path %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header-wrapper">
    <div class="title-area">
      <h1 class="index-title">登記申請推進委員会</h1>
      <div class="index-subtitle">
        登記手続きの中には自分でできる簡単なものもあります。<br>
        節約のために本委員会と一緒に挑戦してみませんか？
      </div>
    </div>

    <div class="top-right-area">
      <ul class="lists-top-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.nickname, "#", class: "header-list" %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header-list" %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path, class: "header-list" %></li>
          <li><%= link_to "新規登録", new_user_registration_path, class: "header-list" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_side_bar.html.erb
<div class="side-bar-wrapper">
  <div class="side-bar">
    <ul id="side-bar-lists">
      <li class="side-bar-list side-bar-list-title" >お手伝いできるお手続一覧</li>
      <li class="side-bar-list delete-mortgage">
        <%= link_to "抵当権抹消登記", new_application_datum_path, class:"side-bar-list-link" %>
        <div class="delete-mortgage-tip">
          <span>住宅ローンを完済したときに<br>ご自宅に登記された金融機関の担保の<br>記録を抹消するための手続きです。<span>
        </div>
      </li>
      <li class="side-bar-list change-address">
        <%= link_to "住所変更登記", "#", class:"side-bar-list-link" %></li>
        <div class="change-address-tip">
        </div>
      <li class="side-bar-list inheritance">
        <%= link_to "相続による所有権移転登記", "#", class:"side-bar-list-link" %>
        <div class="inheritance-tip">
        </div>
      </li>
    </ul>
  </div>
</div>