config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "application_data#index"
  resources :application_data, only: [:index, :new, :create, :destroy]
  resources :application_data do
    collection do
      get "operator_info"
    end
  end
end

app/controllers/application_data_controller.rb
class ApplicationDataController < ApplicationController
  require "wareki"
  require "date"
  before_action :authenticate_user!, except: [:index, :operator_info]

  def index
  end

  def new
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @application_datum_other_party_land_building = ApplicationDatumOtherPartyLandBuilding.new
  end

  def create
    @application_datum_other_party_land_building = ApplicationDatumOtherPartyLandBuilding.new(application_datum_params)
    @applicant = User.find(@application_datum_other_party_land_building.user_id)
    @destination = Destination.find(@application_datum_other_party_land_building.destination_id)
    @branch_destination = BranchDestination.find(@application_datum_other_party_land_building.branch_destination_id)
    @type = Type.find(@application_datum_other_party_land_building.type_id)
    @use = Use.find(@application_datum_other_party_land_building.use_id)
    if @application_datum_other_party_land_building.valid?
      wareki_reason_date
      wareki_application_date
      @application_datum_other_party_land_building.save
    else
      render :new
    end
  end

  def operator_info
  end

  private

  def application_datum_params
    params.require(:application_datum_other_party_land_building).permit(:reason_date, :reason, :receipt_number, :catalog_number, :other_party_address, :other_party_name, :other_party_ceo,
                   :other_party_number, :application_date, :destination_id, :branch_destination_id, :land_prefecture_id, :land_city, :land_number, :land_branch_number, :type_id, :acreage,
                   :building_prefecture_id, :building_city, :building_number, :building_branch_number, :use_id, :construction, :floor_space, :tax).merge(user_id: current_user.id)
  end

  def wareki_reason_date
    reason_date = @application_datum_other_party_land_building.reason_date
    year = reason_date[1]
    month = reason_date[2]
    day = reason_date[3]
    reason_date = "#{year}-#{month}-#{day}"
    @reason_date = Date.parse(reason_date)
  end

  def wareki_application_date
    if @application_datum_other_party_land_building.application_date.present?
      application_date = @application_datum_other_party_land_building.application_date
      @application_date = Date.parse(application_date)
    end
  end
end

app/helpers/application_data_helper.rb
module ApplicationDataHelper
end

app/views/application_data/create.html.erb
<div class="create-wrapper">

  <div class="application-data-top-link">
    <div class="back-top-page">
      <%= link_to "トップページに戻る",root_path %>
    </div>
    <div class="back-input-page">
      <%= link_to "入力ページに戻る", new_application_datum_path %>
    </div>
    <div class="print-button", id="print-button">
      印刷する
    </div>
  </div>


  <div class="application-data-title">
    <h3 >登記申請書</h3>
  </div>

  <div class="application-flame">
    <div class="application-column">
      登記の目的
    </div>
    <div class="application-content">
      抵当権抹消
    </div>
  </div>

  <div class="application-flame">
    <div class="application-column">
      原因
    </div>
    <div class="application-content">
      <%= @reason_date.strftime("%Jf") %>
      <span class="span-create-page"><%= @application_datum_other_party_land_building.reason %></span>
    </div>
  </div>

  <div class="application-flame">
    <div class="application-column">
      抹消すべき登記
    </div>
    <div class="application-content">
      <%= @application_datum_other_party_land_building.receipt_number %>
      <div class="application-content">
        <%= @application_datum_other_party_land_building.catalog_number %>
      </div>
    </div>
  </div>

  <div class="application-flame">
    <div class="application-column">
      権利者
    </div>
    <div class="application-content">
      <%= @applicant.address %>
      <div class="application-content">
        <%= @applicant.name %>
      </div>
    </div>
  </div>

  <div class="application-flame">
    <div class="application-column">
      義務者
    </div>
    <div class="application-content">
      <%= @application_datum_other_party_land_building.other_party_address %>
      <div class="application-content">
        <%= @application_datum_other_party_land_building.other_party_name %>
      </div>
      <div class="application-content">
        <%= @application_datum_other_party_land_building.other_party_ceo %>
      </div>
      <div class="application-content">
        会社法人等番号<span class="span-create-page"><%= @application_datum_other_party_land_building.other_party_number%></span>
      </div>
    </div>
  </div>

  <div class="application-flame">
    <div class="application-column">
      添付書類
    </div>
    <div class="application-content">
      登記識別情報通知<span class="span-create-page">登記原因証明情報</span><span class="span-create-page">代理権限証明情報</span><span class="span-create-page">会社法人等番号</span>
    </div>
  </div>

  <div class="application-flame">
      登記完了証の交付方法<span class="span-create-page">郵送による交付を希望する</span>
  </div>

  <div class="application-flame">
    <div class="application-content">
      <% if @application_date.present? %>
        <%= @application_date.strftime("%Jf") %><span class="span-create-page">申請</span>
      <% else %>
        <span>令和</span><span class="span-create-page">年</span><span class="span-create-page">月</span><span class="span-create-page">日</span><span class="span-create-page">申請</span>
      <% end %>
      <span class="span-create-page"><%= @destination.name %></span>
      <% if @branch_destination.name != "本局" %>
        <span class="span-create-page">
          <%=@branch_destination.name %>
        </span>
      <% end %>
      <span class="span-create-page">御中</span>
    </div>
  </div>

  <div class="application-flame">
    <div class="application-column">
      申請人兼<br>義務者代理人
    </div>
    <div class="application-content">
      <%= @applicant.address %>
      <div class="application-content">
        <%= @applicant.name %>
      </div>
    </div>
  </div>

  <div class="application-flame">
    <div class="application-column">
      登録免許税
    </div>
    <div class="application-content">
      金<%= @application_datum_other_party_land_building.tax %>円
    </div>
  </div>

  <div class="application-real-estate-wrapper">
    不動産の表示

    <div class="real-estate-wapper2">
      <div class="application-real-estate-flame">
        <div class="application-real-estate-column">
        所在
        </div>
        <div class="application-real-estate-content">
          <%= @application_datum_other_party_land_building.land_city %>
        </div>
      </div>

      <div class="application-real-estate-flame">
        <div class="application-real-estate-column">
          地番
        </div>
        <div class="application-real-estate-content">
          <%= @application_datum_other_party_land_building.land_number%>番
          <%= @application_datum_other_party_land_building.land_branch_number%>
        </div>
      </div>

      <div class="application-real-estate-flame">
        <div class="application-real-estate-column">
          地目
        </div>
        <div class="application-real-estate-content">
          <%= @type.name%>
        </div>
      </div>

      <div class="application-real-estate-flame">
        <div class="application-real-estate-column">
          地積
        </div>
        <div class="application-real-estate-content">
          <%= @application_datum_other_party_land_building.acreage %>
        </div>
      </div>
    </div>

    <div class="real-estate-wapper2">
      <div class="application-real-estate-flame">
        <div class="application-real-estate-column">
          所在
        </div>
        <div class="application-real-estate-content">
          <%= @application_datum_other_party_land_building.building_city%>
        </div>
      </div>

      <div class="application-real-estate-flame">
        <div class="application-real-estate-column">
          家屋番号
        </div>
        <div class="application-real-estate-content">
          <%= @application_datum_other_party_land_building.building_number%>番
          <%= @application_datum_other_party_land_building.building_branch_number%>
        </div>
      </div>

      <div class="application-real-estate-flame">
        <div class="application-real-estate-column">
          種類
        </div>
        <div class="application-real-estate-content">
          <%= @use.name%>
        </div>
      </div>

      <div class="application-real-estate-flame">
        <div class="application-real-estate-column"> 
          構造
        </div>
        <div class="application-real-estate-content">
          <%= @application_datum_other_party_land_building.construction%>
        </div>
      </div>

      <div class="application-real-estate-flame">
        <div class="application-real-estate-column"> 
          床面積
        </div>
        <div class="application-real-estate-content">
          <%= @application_datum_other_party_land_building.floor_space%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application_data/index.html.erb
<div class="wrapper">
  <div class="header">
    <%= render "shared/header" %>
  </div>

  <div class="center">
    <div class="left-side">
      <%= render "shared/side_bar" %>
    </div>

    <div class="right-side">
      <div class="right-side-head">
        <div class="select-menu">
          左のメニューバーからご希望の手続きをお選びください。
        </div>
        <div class="top-page-description">
          登記手続きは難しいものばかりと思われるかもしれませんが、<br>
          中にはご自身でも頑張ればできる比較的簡単なものもあります。<br>
          本サイトでは、その比較的簡単な登記手続きについてQ&A形式で<br>
          申請書ができあがるようにしてますので、是非ご活用してください！<br>
        </div>
      </div>

      <div class="right-side-body">
      </div>
      <div class="right-side-foot">
        恐れ入りますが、本サイトで作成した申請書が法務局で受付されなかった場合でも<br>
        当方では責任を負いません。<br>
        誤入力による不備が多いので、入力には細心の注意を払ってください。
      </div>
    </div>
  </div>

  <div class="footer">
    <%= render "shared/footer" %>
  </div>
</div>

app/views/application_data/new.html.erb
<div class="new-page-warpper">
  <div class="application-data-header">
    <div class="application-data-back">
      <%= link_to "トップページに戻る", root_path %>
    </div>
    <div class="application-data-save">
      <%= link_to "入力内容を保存して終了する", "#" %>
    </div>
  </div>

  <div class="application-data-title">
    <h3 id="application-data-title">登記申請書を完成させるための質問事項です。<br>
    金融機関から受領した書類と登記簿謄本をご確認しながら下記の質問にご回答ください。<h3>
  </div>

  <%= render "shared/error_messages", model: @application_datum_other_party_land_building%>

  <%# 入力フォーム %>
  <div class="application-data-main">
    <%= form_with model: @application_datum_other_party_land_building, url: application_data_path, local: true do |f| %>

      <%# 抵当権情報 %>
      <div class="input-item mortgage-info">
        <%= f.label :mortgage_info, "抵当権の情報" %>
        <div class="input-form">
          <%= f.label :reason_date, "・抵当権が消滅した年月日（住宅ローンの最終支払日）" %><br>
            <%= raw sprintf(
                    date_select_ja(
                      f.date_select(
                        :reason_date,
                        class:"reason-date",
                        use_month_numbers: true,
                        prompt:"--",
                        start_year: Time.now.year,
                        end_year: 1960,
                        date_separator: "%s")),
                      "<span>年</span>","<span>月</span>") + "<span>日</span>" %>
        </div>

        <div class=input-form>
          <%= f.label :reason, "・抵当権が消滅した理由（抵当権が消滅したことを証明する書面に記載されてます）" %><br>

          <span class="reason_select">
            <%= f.radio_button :reason, :"解除" %>
            <%= f.label :reason, "解除", {style: "display: inline-block;"} %>
          </span>

          <span class="reason_select">
            <%= f.radio_button :reason, :"放棄" %>
            <%= f.label :reason, "放棄", {style: "display: inline-block;"} %>
          </span>

          <span class="reason_select">
            <%= f.radio_button :reason, :"弁済" %>
            <%= f.label :reason, "弁済", {style: "display: inline-block;"} %>
          </span>

          <span class="reason_select">
            <%= f.radio_button :reason, :"解約" %>
            <%= f.label :reason, "解約", {style: "display: inline-block;"} %>
          </span>

          <span class="reason_select">
            <%= f.radio_button :reason, :"主債務消滅" %>
            <%= f.label :reason, "主債務消滅", {style: "display: inline-block;"} %>
          </span>

          <div class="reason_other">
            <%= f.radio_button :reason, :"", id: "reason-other-button", checked: false %>
            <%= f.label :reason, "その他", {style: "display: inline-block;"} %>
            <%= f.text_field  :unknown, id: "reason-input" %>
          </div>
        </div>

        <div class=input-form>
          <%= f.label :receipt_number, "・消滅した抵当権の受付年月日と番号（例　平成○○年○○月○○日受付第○○号）" %><br>
          <%= f.text_field :receipt_number, :size=> "45", class:"receipt-number", placeholder:"例）平成元年１月１１日受付第１１１１号" %>
        </div>

        <div class=input-form>
          <%= f.label :catalog_number, "・消滅した抵当権の共同担保目録番号（例　（あ）第◯◯／○○号）" %><br>
          <%= f.text_field :catalog_number, :size=> "45", class:"catalog-number", placeholder:"例）（あ）第１００／１２３号" %>
        </div>
      </div>
      <%# /抵当権情報 %>

      <%# 抵当権者情報 %>
      <div class="input-item other-party-info">
        <%= f.label :other_party_info, "抵当権者（金融機関や保証会社）の情報" %>
        <div class="input-form">
          <%= f.label :other_party_address, "・本店所在地（郵便番号不要。都道府県から）" %><br>
          <%= f.text_area :other_party_address, class:"other-party-address", placeholder: "例）福岡県福岡市中央区天神一丁目１番１号\n佐賀ビル１００階" %> 
        </div>
        <div class="input-form">
          <%= f.label :other_party_name, "・商号（株式会社○○銀行や株式会社○○保証など）" %><br>
          <%= f.text_field :other_party_name, class:"other-party-name", placeholder:"例）株式会社住宅ローン銀行" %>  
        </div>
        <div class="input-form">
          <%= f.label :other_party_ceo, "・代表者（代表取締役○○や代表理事○○など）" %><br>
          <%= f.text_field :other_party_ceo, class:"other-party-ceo",placeholder:"例）代表取締役 住宅太郎" %>
        </div>
        <div class="input-form">
          <%= f.label :other_party_number, "・会社法人等番号（12桁の数字）" %><br>
          <%= f.text_field :other_party_number, class:"other-party-number",placeholder:"半角数字でご入力ださい" %>
        </div>
      </div>
      <%# /抵当権者情報 %>

      <%# 申請書提出日、管轄法務局情報 %>
      <div class="input-item destination-info">
        <div class="input-form">
          <%= f.label :application_date, "申請書を法務局に提出する年月日
          （郵送する場合は法務局に到達した日が提出する年月日になります）" %><br>
          <%= f.date_field :application_date, selected: Date.today %>
        </div>
        <div class="input-form">
          <%= simple_format "不動産の所在地を管轄する法務局\n
          （「不動産の市町村名 法務局」で検索すると見つかります）" %>
          <%= f.label :destination_id, "・管轄法務局"%><br>
          <%= f.collection_select(:destination_id, Destination.all, :id, :name,{},{id:"destination"}) %><br>
          <%= f.label :destination_id, "・支局又は出張所（ない場合は、本局を選択してください）"%><br>
          <%= f.collection_select(:branch_destination_id, BranchDestination.all, :id, :name,{},{Id:"branch-destination"}) %>
        </div>
      </div>
      <%# /申請書提出日、管轄法務局情報 %>

      <%# 土地情報 %>
      <div class="input-item land-info">
        <%= f.label :land_prefecture_id, "土地の情報（登記簿謄本通りにご入力ください）" %>
        <div class="input-form">
          <%= f.label :land_prefecture_id, "・都道府県" %><br>
          <%= f.collection_select(:land_prefecture_id, Prefecture.all, :id, :name,{},{class:"prefecture"}) %>
        </div>
        <div class="input-form">
          <%= f.label :land_city, "・所在（例）福岡市中央区天神一丁目"%>
          <%= f.text_area :land_city, class:"city" %>
        </div>
        <div class="input-form">
          <%= f.label :land_number, "・地番（半角数字でご入力ください）" %><br>
          <%= f.text_field :land_number, class:"number" %>
        </div>
        <div class="input-form">
          <%= f.label :land_branch_number, "・枝番（半角数字でご入力ください、ないときは空欄で構いません）"%><br>
          <%= f.text_field :land_branch_number, class:"branch-number" %>
        </div>
        <div class="input-form">
          <%= f.label :type_id, "・地目"%><br>
          <%= f.collection_select(:type_id, Type.all, :id, :name,{},{class:"type"}) %>
        </div>
        <div class="input-form">
          <%= f.label :acreage, "・地積（例 １００・０１平方メートル）" %><br>
          <%= f.text_field :acreage, class:"land-acreage" %>
        </div>
      </div>
      <%# /土地情報 %>

      <%# 建物情報 %>
      <div class="input-item building-info">
        <%= f.label :building_prefecture_id, "建物の情報（登記簿藤本通りにご入力ください）" %>
          <div class="input-form">
            <%= f.label :building_prefecture_id, "都道府県" %><br>
            <%= f.collection_select(:building_prefecture_id, Prefecture.all, :id, :name,{},{class:"prefecture"}) %>
          </div>
          <div class="input-form">
            <%= f.label :building_city, "・所在地（福岡市中央区天神一丁目１番地１）" %><br>
            <%= f.text_area :building_city, class:"city" %>
          </div>
          <div class="input-form">
            <%= f.label :building_number, "・家屋番号（半角数字でご入力ください）" %><br>
            <%= f.text_field :building_number, class:"number", placeholder:"家屋番号" %>
          </div>
          <div class="input-form">
            <%= f.label :building_branch_number, "枝番（半角数字でご入力ください、枝番がないときは空欄で構いません）" %><br>
            <%= f.text_field :building_branch_number, class:"branch-number", placeholder:"枝番" %>
          </div>
          <div class="input-form">
            <%= f.label :use_id, "・種類" %><br>
            <%= f.collection_select(:use_id, Use.all, :id, :name,{},{class:"use"}) %>
          </div>
          <div class="input-form">
            <%= f.label :construction, "・構造（例 木造かわら葺２階建）" %><br>
            <%= f.text_field :construction, class:"construction" %>
          </div>
          <div class="input-form">
            <%= f.label :floor_space, "・床面積" %><br>
            <%= f.text_area :floor_space, class:"floor-space", placeholder: "例）１階 100.01平方メートル\r２階 50.10平方メートル" %>
          </div>
      </div>
      <%# /建物情報 %>

      <%# 登録免許税情報%>
      <div class="input-item tax-info">
        <div class="input-form">
          <%= f.label :tax, "登録免許税額（土地建物の合計数 ✖️ 1000）" %><br>
          <%= f.text_field :tax, class:"tax" %>
        </div>
      </div>
      <%# /登録免許税情報 %>

      <div class="input-item submit-button-area">
        <%= f.submit "入力完了", class:"submit-button" %>
      </div>
    <% end %>
    <%# /入力フォーム%>
  </div>
</div>

app/views/application_data/operator_info.html.erb
<div class="operator-info-wrapper">
  <div class="header">
    <%= render "shared/header" %>
  </div>

  <div class="operator-info-body">
    <div class="operator-info-main">
      <div class="operator-info-title">
       登記推進委員会
      </div>
      <div class="operator-info-table">
        <table border="1">
          <tr class="operator-info-tr">
            <th class="operator-info-item">運営者</th>
            <th class="operator-info-content">佐賀達也</th>
          </tr>
          <tr class="operator-info-tr">
            <td class="operator-info-item">経歴</td>
            <td class="operator-info-content">司法書士業務に9年ほど携わっていた元司法書士です。</td>
          </tr>
          <tr class="operator-info-tr">
            <td class="operator-info-item">メールアドレス</td>
            <td class="operator-info-content">t.saga@yahoo.ne.jp</td>
          </tr>
        </table>
      </div>
      <%= link_to "トップページに戻る", root_path %>
    </div>
  </div>

  <div class="footer">
    <%= render "shared/footer" %>
  </div>
</div>